INSERT INTO cities(governorate,name,code) VALUES
('القاهرة','القاهرة','cairo-cairo'),
('الجيزة','الجيزة','giza-giza'),
('الإسكندرية','الإسكندرية','alexandria-alexandria'),
('الدقهلية','المنصورة','dakahlia-mansoura'),
('البحر الأحمر','الغردقة','red-sea-hurghada'),
('البحيرة','دمنهور','beheira-damanhour'),
('الفيوم','الفيوم','fayoum-fayoum'),
('الغربية','طنطا','gharbia-tanta'),
('الإسماعيلية','الإسماعيلية','ismailia-ismailia'),
('المنوفية','شبين الكوم','monufia-shebin-el-kom'),
('المنيا','المنيا','minya-minya'),
('القليوبية','بنها','qalyubia-banha'),
('الوادي الجديد','الخارجة','new-valley-kharga'),
('السويس','السويس','suez-suez'),
('أسوان','أسوان','aswan-aswan'),
('أسيوط','أسيوط','assiut-assiut'),
('بني سويف','بني سويف','beni-suef-beni-suef'),
('بورسعيد','بورسعيد','port-said-port-said'),
('دمياط','دمياط','damietta-damietta'),
('الشرقية','الزقازيق','sharqia-zagazig'),
('الشرقية','أبو كبير','sharqia-abu-kabir'),
('الشرقية','فاقوس','sharqia-faqous'),
('الشرقية','بلبيس','sharqia-belbeis'),
('الشرقية','العاشر من رمضان','sharqia-10th-ramadan'),
('جنوب سيناء','الطور','south-sinai-el-tor'),
('كفر الشيخ','كفر الشيخ','kafr-el-sheikh-kafr-el-sheikh'),
('مطروح','مرسى مطروح','matrouh-marsa-matrouh'),
('الأقصر','الأقصر','luxor-luxor'),
('قنا','قنا','qena-qena'),
('شمال سيناء','العريش','north-sinai-arish'),
('سوهاج','سوهاج','sohag-sohag')
ON CONFLICT (code) DO UPDATE SET governorate=EXCLUDED.governorate,name=EXCLUDED.name,is_active=true;
