const adminApi = window.KHALASA_API_BASE_URL || (location.protocol === 'file:' ? 'http://localhost:4173' : location.origin);
const adminTitles = { overview:'نظرة عامة', orders:'الطلبات المباشرة', approvals:'طلبات الاعتماد', partners:'المحلات والمندوبون', zones:'مناطق التشغيل', finance:'العمولات والتسويات', support:'الدعم والشكاوى' };
const adminEscape = value => String(value ?? '').replace(/[&<>"']/g, character => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]));
function toast(message){const target=document.getElementById('toast');target.textContent=message;target.classList.add('show');clearTimeout(window.adminToast);window.adminToast=setTimeout(()=>target.classList.remove('show'),2600)}
function adminPage(page,button){document.querySelectorAll('.admin-page').forEach(item=>item.classList.toggle('active',item.id===`admin-${page}`));document.querySelectorAll('[data-admin-page]').forEach(item=>item.classList.toggle('active',item===button));document.getElementById('adminTitle').textContent=adminTitles[page];if(page==='orders')syncAdminOrders()}
function humanStatus(status){return({awaiting_merchant:'بانتظار قبول المحل',preparing:'قيد التجهيز',awaiting_rider:'بانتظار مندوب',assigned:'تم تعيين مندوب',picked_up:'في الطريق',delivered:'مكتمل',cancelled:'ملغي'})[status]||status}
async function syncAdminOrders(){const token=localStorage.getItem('khalasaStaffToken');if(!token)return;try{const response=await fetch(`${adminApi}/v1/admin/orders`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)throw new Error('ADMIN_ORDERS_FAILED');const data=await response.json(),orders=data.orders||[],active=orders.filter(order=>!['delivered','cancelled'].includes(order.status));document.getElementById('liveCount').textContent=active.length;document.getElementById('activeOrders').textContent=active.length;document.getElementById('flowNew').textContent=orders.filter(order=>order.status==='awaiting_merchant').length;document.getElementById('flowPreparing').textContent=orders.filter(order=>order.status==='preparing').length;document.getElementById('flowRider').textContent=orders.filter(order=>order.status==='awaiting_rider').length;document.getElementById('adminOrders').innerHTML=orders.length?orders.map(order=>{const total=Number(order.merchandise_total||0)+Number(order.delivery_fee||0);return `<article class="admin-order"><div><h3>${adminEscape(order.public_code)} · ${adminEscape(order.customer_name)}</h3><p>${adminEscape(order.merchant_name)} · ${adminEscape(order.delivery_address)}</p></div><div><b>${total.toLocaleString('ar-EG')} ج.م</b><small>الدفع: ${order.payment_method==='cod'?'عند الاستلام':adminEscape(order.payment_method)}</small></div><span class="status">${adminEscape(humanStatus(order.status))}</span><button class="table-btn" onclick="toast('سيضاف سجل أحداث الطلب في المرحلة التالية')">تفاصيل</button></article>`}).join(''):'<p class="loading">لا توجد طلبات بعد.</p>'}catch{document.getElementById('adminOrders').innerHTML='<p class="loading">تعذر تحميل الطلبات. تحقق من جلسة الإدارة واتصال الخادم.</p>'}}
function approvePartner(button,message){button.closest('.approval').classList.add('done');button.closest('div').remove();toast(message)}
function createTicket(event){event.preventDefault();event.target.reset();toast('تم حفظ تذكرة الدعم وإسنادها لفريق العمليات')}
syncAdminOrders();setInterval(syncAdminOrders,8000);
