INSERT INTO cities(governorate,name,code) VALUES
('القاهرة','القاهرة','cairo-cairo'),
('القاهرة','حلوان','cairo-helwan'),
('القاهرة','المعادي','cairo-maadi'),
('القاهرة','مدينة نصر','cairo-nasr-city'),
('القاهرة','مصر الجديدة','cairo-heliopolis'),
('القاهرة','القاهرة الجديدة','cairo-new-cairo'),
('القاهرة','التجمع الخامس','cairo-fifth-settlement'),
('القاهرة','الشروق','cairo-shorouk'),
('القاهرة','بدر','cairo-badr'),
('القاهرة','15 مايو','cairo-15-may'),
('القاهرة','العاصمة الإدارية الجديدة','cairo-new-capital'),
('الجيزة','الجيزة','giza-giza'),
('الجيزة','6 أكتوبر','giza-6-october'),
('الجيزة','الشيخ زايد','giza-sheikh-zayed'),
('الجيزة','الحوامدية','giza-hawamdeya'),
('الجيزة','البدرشين','giza-badrashin'),
('الجيزة','الصف','giza-saff'),
('الجيزة','أطفيح','giza-atfih'),
('الجيزة','العياط','giza-ayat'),
('الجيزة','الواحات البحرية','giza-bahariya'),
('الجيزة','منشأة القناطر','giza-manshaat-al-qanater'),
('الجيزة','أوسيم','giza-ossim'),
('الجيزة','كرداسة','giza-kerdasa'),
('الجيزة','أبو النمرس','giza-abu-nomros'),
('الإسكندرية','الإسكندرية','alexandria-alexandria'),
('الإسكندرية','برج العرب','alexandria-borg-el-arab'),
('الإسكندرية','برج العرب الجديدة','alexandria-new-borg-el-arab'),
('الإسكندرية','العجمي','alexandria-agami'),
('الإسكندرية','المنتزه','alexandria-montaza'),
('الدقهلية','المنصورة','dakahlia-mansoura'),
('الدقهلية','طلخا','dakahlia-talkha'),
('الدقهلية','ميت غمر','dakahlia-mit-ghamr'),
('الدقهلية','دكرنس','dakahlia-dekirnis'),
('الدقهلية','أجا','dakahlia-aga'),
('الدقهلية','منية النصر','dakahlia-menyet-el-nasr'),
('الدقهلية','السنبلاوين','dakahlia-sinbillawin'),
('الدقهلية','بني عبيد','dakahlia-bani-ebeid'),
('الدقهلية','المنزلة','dakahlia-manzala'),
('الدقهلية','الجمالية','dakahlia-gamaliya'),
('الدقهلية','المطرية','dakahlia-matariya'),
('الدقهلية','بلقاس','dakahlia-belqas'),
('الدقهلية','شربين','dakahlia-sherbin'),
('الدقهلية','نبروه','dakahlia-nabroh'),
('الدقهلية','جمصة','dakahlia-gamasa'),
('البحر الأحمر','الغردقة','red-sea-hurghada'),
('البحر الأحمر','رأس غارب','red-sea-ras-gharib'),
('البحر الأحمر','سفاجا','red-sea-safaga'),
('البحر الأحمر','القصير','red-sea-quseir'),
('البحر الأحمر','مرسى علم','red-sea-marsa-alam'),
('البحر الأحمر','الشلاتين','red-sea-shalateen'),
('البحر الأحمر','حلايب','red-sea-halaib'),
('البحيرة','دمنهور','beheira-damanhour'),
('البحيرة','كفر الدوار','beheira-kafr-el-dawwar'),
('البحيرة','رشيد','beheira-rasheed'),
('البحيرة','إدكو','beheira-edku'),
('البحيرة','أبو حمص','beheira-abu-hummus'),
('البحيرة','أبو المطامير','beheira-abu-el-matamir'),
('البحيرة','الدلنجات','beheira-delengat'),
('البحيرة','المحمودية','beheira-mahmoudiya'),
('البحيرة','الرحمانية','beheira-rahmaniya'),
('البحيرة','إيتاي البارود','beheira-itay-el-barud'),
('البحيرة','حوش عيسى','beheira-hosh-issa'),
('البحيرة','شبراخيت','beheira-shubrakhit'),
('البحيرة','كوم حمادة','beheira-kom-hamada'),
('البحيرة','بدر','beheira-badr'),
('البحيرة','وادي النطرون','beheira-wadi-el-natrun'),
('البحيرة','النوبارية الجديدة','beheira-new-nubaria'),
('الفيوم','الفيوم','fayoum-fayoum'),
('الفيوم','سنورس','fayoum-sinnuris'),
('الفيوم','إطسا','fayoum-itsa'),
('الفيوم','طامية','fayoum-tamiya'),
('الفيوم','أبشواي','fayoum-ibshaway'),
('الفيوم','يوسف الصديق','fayoum-youssef-el-seddik'),
('الغربية','طنطا','gharbia-tanta'),
('الغربية','المحلة الكبرى','gharbia-mahalla-el-kubra'),
('الغربية','كفر الزيات','gharbia-kafr-el-zayat'),
('الغربية','زفتى','gharbia-zifta'),
('الغربية','السنطة','gharbia-santa'),
('الغربية','قطور','gharbia-qutur'),
('الغربية','بسيون','gharbia-basyoun'),
('الغربية','سمنود','gharbia-samanoud'),
('الإسماعيلية','الإسماعيلية','ismailia-ismailia'),
('الإسماعيلية','فايد','ismailia-fayed'),
('الإسماعيلية','القنطرة شرق','ismailia-qantara-east'),
('الإسماعيلية','القنطرة غرب','ismailia-qantara-west'),
('الإسماعيلية','التل الكبير','ismailia-tell-el-kebir'),
('الإسماعيلية','أبو صوير','ismailia-abu-suweir'),
('الإسماعيلية','القصاصين الجديدة','ismailia-new-qassasin'),
('المنوفية','شبين الكوم','monufia-shebin-el-kom'),
('المنوفية','منوف','monufia-menouf'),
('المنوفية','مدينة السادات','monufia-sadat-city'),
('المنوفية','أشمون','monufia-ashmoun'),
('المنوفية','الباجور','monufia-bagour'),
('المنوفية','قويسنا','monufia-quwaysna'),
('المنوفية','بركة السبع','monufia-birket-el-sabaa'),
('المنوفية','تلا','monufia-tala'),
('المنوفية','الشهداء','monufia-shohadaa'),
('المنوفية','سرس الليان','monufia-sers-el-layan'),
('المنيا','المنيا','minya-minya'),
('المنيا','المنيا الجديدة','minya-new-minya'),
('المنيا','ملوي','minya-mallawi'),
('المنيا','بني مزار','minya-beni-mazar'),
('المنيا','مغاغة','minya-maghagha'),
('المنيا','سمالوط','minya-samalout'),
('المنيا','مطاي','minya-matayi'),
('المنيا','أبو قرقاص','minya-abu-qurqas'),
('المنيا','دير مواس','minya-deir-mawas'),
('المنيا','العدوة','minya-el-idwa'),
('القليوبية','بنها','qalyubia-banha'),
('القليوبية','شبرا الخيمة','qalyubia-shubra-el-kheima'),
('القليوبية','قليوب','qalyubia-qalyub'),
('القليوبية','العبور','qalyubia-obour'),
('القليوبية','الخانكة','qalyubia-khanka'),
('القليوبية','القناطر الخيرية','qalyubia-qanater-el-khairiya'),
('القليوبية','كفر شكر','qalyubia-kafr-shukr'),
('القليوبية','طوخ','qalyubia-toukh'),
('القليوبية','شبين القناطر','qalyubia-shebin-el-qanater'),
('القليوبية','الخصوص','qalyubia-khosous'),
('القليوبية','قها','qalyubia-qaha'),
('الوادي الجديد','الخارجة','new-valley-kharga'),
('الوادي الجديد','الداخلة','new-valley-dakhla'),
('الوادي الجديد','باريس','new-valley-paris'),
('الوادي الجديد','بلاط','new-valley-balat'),
('الوادي الجديد','الفرافرة','new-valley-farafra'),
('السويس','السويس','suez-suez'),
('السويس','الأربعين','suez-arbaeen'),
('السويس','عتاقة','suez-ataqa'),
('السويس','فيصل','suez-faisal'),
('السويس','الجناين','suez-ganayen'),
('أسوان','أسوان','aswan-aswan'),
('أسوان','أسوان الجديدة','aswan-new-aswan'),
('أسوان','إدفو','aswan-edfu'),
('أسوان','كوم أمبو','aswan-kom-ombo'),
('أسوان','دراو','aswan-daraw'),
('أسوان','نصر النوبة','aswan-nasr-el-nuba'),
('أسوان','كلابشة','aswan-kalabsha'),
('أسوان','أبو سمبل','aswan-abu-simbel'),
('أسوان','الرديسية','aswan-radisiya'),
('أسوان','البصيلية','aswan-bisaliya'),
('أسيوط','أسيوط','assiut-assiut'),
('أسيوط','أسيوط الجديدة','assiut-new-assiut'),
('أسيوط','ديروط','assiut-dayrout'),
('أسيوط','القوصية','assiut-qusiya'),
('أسيوط','منفلوط','assiut-manflut'),
('أسيوط','أبنوب','assiut-abnoub'),
('أسيوط','أبو تيج','assiut-abu-tig'),
('أسيوط','الغنايم','assiut-ghanayem'),
('أسيوط','البداري','assiut-badari'),
('أسيوط','ساحل سليم','assiut-sahel-selim'),
('أسيوط','صدفا','assiut-sodfa'),
('أسيوط','الفتح','assiut-fath'),
('بني سويف','بني سويف','beni-suef-beni-suef'),
('بني سويف','بني سويف الجديدة','beni-suef-new-beni-suef'),
('بني سويف','الواسطى','beni-suef-wasta'),
('بني سويف','ناصر','beni-suef-nasser'),
('بني سويف','الفشن','beni-suef-fashn'),
('بني سويف','ببا','beni-suef-biba'),
('بني سويف','إهناسيا','beni-suef-ihnasya'),
('بني سويف','سمسطا','beni-suef-sumusta'),
('بورسعيد','بورسعيد','port-said-port-said'),
('بورسعيد','بورفؤاد','port-said-port-fouad'),
('دمياط','دمياط','damietta-damietta'),
('دمياط','دمياط الجديدة','damietta-new-damietta'),
('دمياط','رأس البر','damietta-ras-el-bar'),
('دمياط','كفر سعد','damietta-kafr-saad'),
('دمياط','فارسكور','damietta-faraskour'),
('دمياط','الزرقا','damietta-zarqa'),
('دمياط','كفر البطيخ','damietta-kafr-el-batikh'),
('دمياط','ميت أبو غالب','damietta-mit-abu-ghalib'),
('دمياط','الروضة','damietta-rawda'),
('دمياط','عزبة البرج','damietta-ezbet-el-borg'),
('الشرقية','الزقازيق','sharqia-zagazig'),
('الشرقية','كفر صقر','sharqia-kafr-saqr'),
('الشرقية','أبو كبير','sharqia-abu-kabir'),
('الشرقية','فاقوس','sharqia-faqous'),
('الشرقية','بلبيس','sharqia-belbeis'),
('الشرقية','العاشر من رمضان','sharqia-10th-ramadan'),
('الشرقية','منيا القمح','sharqia-menya-el-qamh'),
('الشرقية','أبو حماد','sharqia-abu-hammad'),
('الشرقية','الحسينية','sharqia-husseiniya'),
('الشرقية','ديرب نجم','sharqia-deirb-negm'),
('الشرقية','ههيا','sharqia-hehya'),
('الشرقية','الإبراهيمية','sharqia-ibrahimiya'),
('الشرقية','مشتول السوق','sharqia-mashtoul-el-souk'),
('الشرقية','القرين','sharqia-qurayn'),
('الشرقية','صان الحجر','sharqia-san-el-hagar'),
('الشرقية','أولاد صقر','sharqia-awlad-saqr'),
('الشرقية','القنايات','sharqia-qanayat'),
('جنوب سيناء','الطور','south-sinai-el-tor'),
('جنوب سيناء','شرم الشيخ','south-sinai-sharm-el-sheikh'),
('جنوب سيناء','دهب','south-sinai-dahab'),
('جنوب سيناء','نويبع','south-sinai-nuweiba'),
('جنوب سيناء','طابا','south-sinai-taba'),
('جنوب سيناء','رأس سدر','south-sinai-ras-sedr'),
('جنوب سيناء','أبو رديس','south-sinai-abu-rudeis'),
('جنوب سيناء','أبو زنيمة','south-sinai-abu-zenima'),
('جنوب سيناء','سانت كاترين','south-sinai-saint-catherine'),
('كفر الشيخ','كفر الشيخ','kafr-el-sheikh-kafr-el-sheikh'),
('كفر الشيخ','دسوق','kafr-el-sheikh-desouk'),
('كفر الشيخ','بلطيم','kafr-el-sheikh-baltim'),
('كفر الشيخ','الحامول','kafr-el-sheikh-hamoul'),
('كفر الشيخ','بيلا','kafr-el-sheikh-biyala'),
('كفر الشيخ','البرلس','kafr-el-sheikh-burullus'),
('كفر الشيخ','فوه','kafr-el-sheikh-fuwa'),
('كفر الشيخ','مطوبس','kafr-el-sheikh-mutubas'),
('كفر الشيخ','قلين','kafr-el-sheikh-qallin'),
('كفر الشيخ','سيدي سالم','kafr-el-sheikh-sidi-salem'),
('كفر الشيخ','الرياض','kafr-el-sheikh-riyadh'),
('مطروح','مرسى مطروح','matrouh-marsa-matrouh'),
('مطروح','الحمام','matrouh-hamam'),
('مطروح','العلمين','matrouh-alamein'),
('مطروح','الضبعة','matrouh-dabaa'),
('مطروح','سيدي براني','matrouh-sidi-barrani'),
('مطروح','السلوم','matrouh-salloum'),
('مطروح','سيوة','matrouh-siwa'),
('مطروح','النجيلة','matrouh-negila'),
('الأقصر','الأقصر','luxor-luxor'),
('الأقصر','الأقصر الجديدة','luxor-new-luxor'),
('الأقصر','طيبة الجديدة','luxor-new-thebes'),
('الأقصر','إسنا','luxor-esna'),
('الأقصر','أرمنت','luxor-armant'),
('الأقصر','الطود','luxor-tod'),
('الأقصر','الزينية','luxor-ziniya'),
('الأقصر','القرنة','luxor-qurna'),
('قنا','قنا','qena-qena'),
('قنا','قنا الجديدة','qena-new-qena'),
('قنا','نجع حمادي','qena-nag-hammadi'),
('قنا','دشنا','qena-dishna'),
('قنا','قفط','qena-qift'),
('قنا','قوص','qena-qus'),
('قنا','نقادة','qena-naqada'),
('قنا','أبو تشت','qena-abu-tesht'),
('قنا','فرشوط','qena-farshout'),
('قنا','الوقف','qena-waqf'),
('شمال سيناء','العريش','north-sinai-arish'),
('شمال سيناء','بئر العبد','north-sinai-bir-el-abd'),
('شمال سيناء','الشيخ زويد','north-sinai-sheikh-zuweid'),
('شمال سيناء','رفح','north-sinai-rafah'),
('شمال سيناء','الحسنة','north-sinai-hasna'),
('شمال سيناء','نخل','north-sinai-nakhl'),
('سوهاج','سوهاج','sohag-sohag'),
('سوهاج','سوهاج الجديدة','sohag-new-sohag'),
('سوهاج','أخميم','sohag-akhmim'),
('سوهاج','جرجا','sohag-girga'),
('سوهاج','طهطا','sohag-tahta'),
('سوهاج','البلينا','sohag-balyana'),
('سوهاج','المراغة','sohag-maragha'),
('سوهاج','المنشأة','sohag-munshaah'),
('سوهاج','دار السلام','sohag-dar-el-salam'),
('سوهاج','جهينة','sohag-juhayna'),
('سوهاج','ساقلته','sohag-saqalta'),
('سوهاج','طما','sohag-tima')
ON CONFLICT (code) DO UPDATE
SET governorate=EXCLUDED.governorate,
    name=EXCLUDED.name,
    is_active=true;
