import 'dotenv/config';
import crypto from 'node:crypto';
import express from 'express';
import cors from 'cors';
import jwt from 'jsonwebtoken';
import pg from 'pg';
const { Pool } = pg;

const required = ['DATABASE_URL', 'JWT_SECRET'];
for (const name of required) if (!process.env[name]) throw new Error(`${name} is required`);
const app = express();
const port = Number(process.env.PORT || 8080);
const commissionRate = Number(process.env.PLATFORM_COMMISSION_RATE || 0.12);
const allowedOrigins = (process.env.CORS_ORIGINS || '').split(',').filter(Boolean);
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: process.env.NODE_ENV === 'production' ? { rejectUnauthorized: false } : false });
app.use(cors({ origin(origin, callback) { if (!origin || allowedOrigins.includes(origin)) return callback(null, true); callback(new Error('CORS_NOT_ALLOWED')); } }));
app.use(express.json({ limit: '1mb' }));

const asyncRoute = handler => (req, res, next) => Promise.resolve(handler(req, res, next)).catch(next);
const publicCode = () => `KH-${Date.now().toString(36).toUpperCase()}-${crypto.randomBytes(2).toString('hex').toUpperCase()}`;
const otpHash = otp => crypto.createHash('sha256').update(String(otp)).digest('hex');
function tokenFor(user) { return jwt.sign({ sub: user.id, role: user.role, phone: user.phone }, process.env.JWT_SECRET, { expiresIn: '7d' }); }
function auth(...roles) { return (req, res, next) => { try { const raw = req.headers.authorization?.replace(/^Bearer\s+/i, ''); if (!raw) return res.status(401).json({ error: 'AUTH_REQUIRED' }); const user = jwt.verify(raw, process.env.JWT_SECRET); if (roles.length && !roles.includes(user.role)) return res.status(403).json({ error: 'FORBIDDEN' }); req.user = user; next(); } catch { res.status(401).json({ error: 'INVALID_TOKEN' }); } }; }
const cityPermissions = ['orders.read','orders.manage','riders.read','riders.manage','partners.request'];
function normalizePermissions(value = {}) { return Object.fromEntries(cityPermissions.map(key => [key, value[key] === true])); }
function cityPermission(permission) { return asyncRoute(async (req, res, next) => {
  if (req.user.role === 'admin') { req.cityScope = null; return next(); }
  const result = await pool.query(`SELECT a.city_id,a.permissions,c.name city_name,c.governorate FROM city_admin_assignments a JOIN cities c ON c.id=a.city_id WHERE a.user_id=$1 AND a.is_active=true AND c.is_active=true`, [req.user.sub]);
  if (!result.rowCount) return res.status(403).json({ error:'CITY_ACCESS_DISABLED' });
  const assignment = result.rows[0];
  if (assignment.permissions?.[permission] !== true) return res.status(403).json({ error:'CITY_PERMISSION_REQUIRED', permission });
  req.cityScope = assignment;
  next();
}); }
function transitionAllowed(from, to) { return ({ awaiting_merchant:['preparing','cancelled'], preparing:['awaiting_rider','cancelled'], awaiting_rider:['assigned','cancelled'], assigned:['picked_up','cancelled'], picked_up:['delivered'], delivered:[], cancelled:[] })[from]?.includes(to); }

app.get('/health', asyncRoute(async (_req, res) => { await pool.query('SELECT 1'); res.json({ ok: true, service: 'khalasa-api' }); }));

app.post('/v1/staff/login', asyncRoute(async (req,res)=>{const phone=String(req.body.phone||''),accessCode=String(req.body.accessCode||'');if(!/^01\d{9}$/.test(phone)||accessCode.length<8)return res.status(400).json({error:'INVALID_STAFF_LOGIN'});if(phone===process.env.OWNER_PHONE&&process.env.OWNER_ACCESS_CODE){const valid=crypto.timingSafeEqual(crypto.createHash('sha256').update(accessCode).digest(),crypto.createHash('sha256').update(process.env.OWNER_ACCESS_CODE).digest());if(!valid)return res.status(401).json({error:'INVALID_STAFF_LOGIN'});const owner=await pool.query(`INSERT INTO users(role,phone,full_name,is_phone_verified) VALUES('admin',$1,'مالك خالصة',true) ON CONFLICT(phone) DO UPDATE SET role='admin',is_phone_verified=true,updated_at=now() RETURNING id,role,phone,full_name`,[phone]);const user=owner.rows[0];return res.json({token:tokenFor(user),user:{id:user.id,role:user.role,phone:user.phone,fullName:user.full_name}});}const found=await pool.query(`SELECT u.id,u.role,u.phone,u.full_name,sc.password_hash FROM users u JOIN staff_credentials sc ON sc.user_id=u.id AND sc.is_active=true WHERE u.phone=$1 AND u.role IN ('admin','city_admin')`,[phone]);if(!found.rowCount)return res.status(401).json({error:'INVALID_STAFF_LOGIN'});const user=found.rows[0];const check=await pool.query('SELECT crypt($1,$2)=$2 AS valid',[accessCode,user.password_hash]);if(!check.rows[0].valid)return res.status(401).json({error:'INVALID_STAFF_LOGIN'});res.json({token:tokenFor(user),user:{id:user.id,role:user.role,phone:user.phone,fullName:user.full_name}});}));
app.get('/v1/admin/me',auth('admin'),asyncRoute(async(req,res)=>res.json({ok:true,user:req.user})));
app.get('/v1/admin/main-users',auth('admin'),asyncRoute(async(_req,res)=>{const rows=await pool.query(`SELECT u.id,u.full_name,u.phone,COALESCE(sc.is_active,true) is_active FROM users u LEFT JOIN staff_credentials sc ON sc.user_id=u.id WHERE u.role='admin' ORDER BY u.created_at`);res.json({users:rows.rows});}));
app.post('/v1/admin/main-users',auth('admin'),asyncRoute(async(req,res)=>{const {fullName,phone,accessCode}=req.body;if(!fullName||!/^01\d{9}$/.test(String(phone||''))||String(accessCode||'').length<8)return res.status(400).json({error:'ADMIN_USER_FIELDS_REQUIRED'});const client=await pool.connect();try{await client.query('BEGIN');let user=await client.query('SELECT id,role FROM users WHERE phone=$1',[phone]);if(user.rowCount&&user.rows[0].role!=='admin'){await client.query('ROLLBACK');return res.status(409).json({error:'PHONE_BELONGS_TO_ANOTHER_ROLE'});}if(!user.rowCount)user=await client.query(`INSERT INTO users(role,phone,full_name,is_phone_verified) VALUES('admin',$1,$2,true) RETURNING id`,[phone,fullName]);else await client.query('UPDATE users SET full_name=$1,updated_at=now() WHERE id=$2',[fullName,user.rows[0].id]);await client.query(`INSERT INTO staff_credentials(user_id,password_hash,is_active) VALUES($1,crypt($2,gen_salt('bf')),true) ON CONFLICT(user_id) DO UPDATE SET password_hash=crypt($2,gen_salt('bf')),is_active=true,updated_at=now()`,[user.rows[0].id,accessCode]);await client.query(`INSERT INTO admin_audit_log(actor_user_id,target_user_id,action,details) VALUES($1,$2,'main_admin.saved',$3::jsonb)`,[req.user.sub,user.rows[0].id,JSON.stringify({phone})]);await client.query('COMMIT');res.status(201).json({ok:true});}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}}));
app.patch('/v1/admin/main-users/:id',auth('admin'),asyncRoute(async(req,res)=>{if(req.params.id===req.user.sub)return res.status(409).json({error:'CANNOT_DISABLE_SELF'});const row=await pool.query(`UPDATE staff_credentials SET is_active=$1,updated_at=now() WHERE user_id=$2 RETURNING user_id,is_active`,[req.body.isActive===true,req.params.id]);if(!row.rowCount)return res.status(404).json({error:'ADMIN_USER_NOT_FOUND'});res.json({user:row.rows[0]});}));

// A real SMS provider must replace this endpoint before production. It never sends or exposes an OTP in production.
app.post('/v1/auth/request-otp', asyncRoute(async (req, res) => {
  const phone = String(req.body.phone || ''); if (!/^01\d{9}$/.test(phone)) return res.status(400).json({ error: 'INVALID_EGYPTIAN_PHONE' });
  if (process.env.NODE_ENV === 'production' && process.env.OTP_PROVIDER === 'disabled') return res.status(503).json({ error: 'OTP_PROVIDER_NOT_CONFIGURED' });
  res.status(202).json({ accepted: true, message: 'OTP dispatch queued' });
}));
app.post('/v1/auth/session', asyncRoute(async (req, res) => {
  const { phone, fullName } = req.body; if (!/^01\d{9}$/.test(String(phone || '')) || !fullName) return res.status(400).json({ error: 'PHONE_AND_NAME_REQUIRED' });
  // New public registrations are always customers. Merchant, rider and staff roles are created only by the approval workflow.
  const existing = await pool.query('SELECT id, role, phone, full_name FROM users WHERE phone=$1', [phone]);
  if (existing.rowCount) return res.json({ token: tokenFor(existing.rows[0]), user: existing.rows[0] });
  const result = await pool.query(`INSERT INTO users(role, phone, full_name, is_phone_verified) VALUES('customer',$1,$2,$3) RETURNING id, role, phone, full_name`, [phone, fullName, process.env.NODE_ENV !== 'production']);
  const user = result.rows[0]; res.json({ token: tokenFor(user), user });
}));

app.post('/v1/orders', auth('customer'), asyncRoute(async (req, res) => {
  const { merchantId, items, deliveryAddress, deliveryLat, deliveryLng, paymentMethod = 'cod' } = req.body;
  if (!merchantId || !Array.isArray(items) || !items.length || !deliveryAddress) return res.status(400).json({ error: 'ORDER_FIELDS_REQUIRED' });
  if (!['cod','wallet','card'].includes(paymentMethod)) return res.status(400).json({ error: 'INVALID_PAYMENT_METHOD' });
  const normalized = items.map(item => ({ productName: String(item.productName || item.name || '').trim(), quantity: Number(item.quantity || item.qty), unitPrice: Number(item.unitPrice || item.price) }));
  if (normalized.some(item => !item.productName || !Number.isInteger(item.quantity) || item.quantity < 1 || !Number.isFinite(item.unitPrice) || item.unitPrice < 0)) return res.status(400).json({ error: 'INVALID_ITEMS' });
  const merchandiseTotal = normalized.reduce((sum, item) => sum + item.quantity * item.unitPrice, 0); const deliveryFee = 20; const otp = crypto.randomInt(1000, 10000).toString();
  const client = await pool.connect();
  try { await client.query('BEGIN'); const merchant = await client.query('SELECT city_id,category FROM merchants WHERE id=$1 AND verification=$2',[merchantId,'approved']); if(!merchant.rowCount){await client.query('ROLLBACK');return res.status(404).json({error:'MERCHANT_NOT_AVAILABLE'});} const selected=await client.query(`SELECT calculation_type,value,minimum_amount,maximum_amount FROM commission_rules WHERE is_active=true AND (city_id IS NULL OR city_id=$1) AND (merchant_category IS NULL OR merchant_category=$2) ORDER BY (city_id IS NOT NULL)::int DESC,(merchant_category IS NOT NULL)::int DESC,created_at DESC LIMIT 1`,[merchant.rows[0].city_id,merchant.rows[0].category]);const rule=selected.rows[0];let commission=rule?(rule.calculation_type==='fixed'?Number(rule.value):merchandiseTotal*Number(rule.value)/100):merchandiseTotal*commissionRate;if(rule){commission=Math.max(commission,Number(rule.minimum_amount||0));if(rule.maximum_amount!=null)commission=Math.min(commission,Number(rule.maximum_amount));}commission=Number(Math.min(commission,merchandiseTotal).toFixed(2));const merchantPayout=Number((merchandiseTotal-commission).toFixed(2));const created = await client.query(`INSERT INTO orders(public_code,customer_id,merchant_id,city_id,delivery_address,delivery_lat,delivery_lng,payment_method,merchandise_total,delivery_fee,platform_commission,merchant_payout,delivery_otp_hash) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING *`, [publicCode(), req.user.sub, merchantId, merchant.rows[0].city_id, deliveryAddress, deliveryLat || null, deliveryLng || null, paymentMethod, merchandiseTotal, deliveryFee, commission, merchantPayout, otpHash(otp)]); const order = created.rows[0]; for (const item of normalized) await client.query('INSERT INTO order_items(order_id,product_name,quantity,unit_price) VALUES($1,$2,$3,$4)', [order.id, item.productName, item.quantity, item.unitPrice]); await client.query('INSERT INTO order_events(order_id,actor_user_id,status,note) VALUES($1,$2,$3,$4)', [order.id, req.user.sub, 'awaiting_merchant', 'تم إنشاء الطلب']); await client.query('COMMIT'); res.status(201).json({ order: { ...order, deliveryOtp: process.env.NODE_ENV === 'production' ? undefined : otp } }); } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); }
}));

app.get('/v1/merchant/orders', auth('merchant'), asyncRoute(async (req, res) => { const rows = await pool.query(`SELECT o.* FROM orders o JOIN merchants m ON m.id=o.merchant_id WHERE m.owner_user_id=$1 AND o.status IN ('awaiting_merchant','preparing') ORDER BY o.created_at DESC`, [req.user.sub]); res.json({ orders: rows.rows }); }));
app.post('/v1/orders/:id/merchant-accept', auth('merchant'), asyncRoute(async (req, res) => { const prepMinutes = Number(req.body.prepMinutes || 20); const order = await pool.query(`SELECT o.* FROM orders o JOIN merchants m ON m.id=o.merchant_id WHERE o.id=$1 AND m.owner_user_id=$2`, [req.params.id, req.user.sub]); if (!order.rowCount) return res.status(404).json({ error: 'ORDER_NOT_FOUND' }); if (!transitionAllowed(order.rows[0].status, 'preparing')) return res.status(409).json({ error: 'INVALID_STATE' }); await pool.query(`UPDATE orders SET status='preparing',prep_minutes=$1,updated_at=now() WHERE id=$2`, [prepMinutes, req.params.id]); await pool.query(`INSERT INTO order_events(order_id,actor_user_id,status,note) VALUES($1,$2,'preparing',$3)`, [req.params.id, req.user.sub, `وقت التجهيز ${prepMinutes} دقيقة`]); res.json({ ok:true }); }));
app.post('/v1/orders/:id/ready', auth('merchant'), asyncRoute(async (req, res) => { const result = await pool.query(`UPDATE orders SET status='awaiting_rider',updated_at=now() WHERE id=$1 AND status='preparing' RETURNING id`, [req.params.id]); if (!result.rowCount) return res.status(409).json({ error:'INVALID_STATE' }); await pool.query(`INSERT INTO order_events(order_id,actor_user_id,status,note) VALUES($1,$2,'awaiting_rider','الطلب جاهز للاستلام')`, [req.params.id,req.user.sub]); res.json({ ok:true }); }));
app.get('/v1/rider/offers', auth('rider'), asyncRoute(async (_req, res) => { const rows = await pool.query(`SELECT id,public_code,merchant_id,delivery_address,delivery_fee,created_at FROM orders WHERE status='awaiting_rider' ORDER BY created_at ASC LIMIT 20`); res.json({ orders:rows.rows }); }));
app.post('/v1/orders/:id/rider-accept', auth('rider'), asyncRoute(async (req,res) => { const rider = await pool.query('SELECT id FROM riders WHERE user_id=$1 AND verification=$2 AND is_available=true',[req.user.sub,'approved']); if(!rider.rowCount) return res.status(403).json({error:'RIDER_NOT_AVAILABLE_OR_APPROVED'}); const result=await pool.query(`UPDATE orders SET status='assigned',rider_id=$1,updated_at=now() WHERE id=$2 AND status='awaiting_rider' RETURNING id`,[rider.rows[0].id,req.params.id]); if(!result.rowCount)return res.status(409).json({error:'ORDER_ALREADY_TAKEN'}); await pool.query(`INSERT INTO order_events(order_id,actor_user_id,status,note) VALUES($1,$2,'assigned','تم قبول الطلب بواسطة المندوب')`,[req.params.id,req.user.sub]);res.json({ok:true}); }));
app.post('/v1/orders/:id/deliver', auth('rider'), asyncRoute(async (req,res) => { const order=await pool.query('SELECT * FROM orders WHERE id=$1',[req.params.id]); if(!order.rowCount)return res.status(404).json({error:'ORDER_NOT_FOUND'}); if(order.rows[0].status!=='picked_up'||otpHash(req.body.otp)!==order.rows[0].delivery_otp_hash)return res.status(409).json({error:'INVALID_DELIVERY_CONFIRMATION'}); await pool.query(`UPDATE orders SET status='delivered',updated_at=now() WHERE id=$1`,[req.params.id]);await pool.query(`INSERT INTO order_events(order_id,actor_user_id,status,note) VALUES($1,$2,'delivered','تم التسليم برمز العميل')`,[req.params.id,req.user.sub]);res.json({ok:true}); }));
app.get('/v1/admin/orders', auth('admin','support'), asyncRoute(async (_req,res)=>{const rows=await pool.query(`SELECT o.*,u.full_name customer_name,m.display_name merchant_name FROM orders o JOIN users u ON u.id=o.customer_id JOIN merchants m ON m.id=o.merchant_id ORDER BY o.created_at DESC LIMIT 200`);res.json({orders:rows.rows});}));

app.get('/v1/admin/cities', auth('admin'), asyncRoute(async (_req,res)=>{const rows=await pool.query(`SELECT c.*,count(DISTINCT a.user_id)::int admin_count FROM cities c LEFT JOIN city_admin_assignments a ON a.city_id=c.id AND a.is_active=true GROUP BY c.id ORDER BY c.governorate,c.name`);res.json({cities:rows.rows});}));
app.post('/v1/admin/cities', auth('admin'), asyncRoute(async (req,res)=>{const {governorate,name,code}=req.body;if(!governorate||!name||!/^[a-z0-9-]{3,60}$/.test(String(code||'')))return res.status(400).json({error:'CITY_FIELDS_REQUIRED'});const row=await pool.query(`INSERT INTO cities(governorate,name,code) VALUES($1,$2,$3) RETURNING *`,[governorate,name,code]);res.status(201).json({city:row.rows[0]});}));
app.get('/v1/admin/city-users', auth('admin'), asyncRoute(async (_req,res)=>{const rows=await pool.query(`SELECT u.id,u.full_name,u.phone,a.city_id,c.name city_name,c.governorate,a.permissions,a.is_active,a.updated_at FROM city_admin_assignments a JOIN users u ON u.id=a.user_id JOIN cities c ON c.id=a.city_id ORDER BY c.name,u.full_name`);res.json({users:rows.rows});}));
app.post('/v1/admin/city-users', auth('admin'), asyncRoute(async (req,res)=>{const {fullName,phone,cityId,accessCode}=req.body;if(!fullName||!/^01\d{9}$/.test(String(phone||''))||!cityId||String(accessCode||'').length<8)return res.status(400).json({error:'CITY_USER_FIELDS_OR_CODE_REQUIRED'});const permissions=normalizePermissions(req.body.permissions);const client=await pool.connect();try{await client.query('BEGIN');let user=await client.query('SELECT id,role FROM users WHERE phone=$1',[phone]);if(user.rowCount&&user.rows[0].role!=='city_admin'){await client.query('ROLLBACK');return res.status(409).json({error:'PHONE_BELONGS_TO_ANOTHER_ROLE'});}if(!user.rowCount)user=await client.query(`INSERT INTO users(role,phone,full_name,is_phone_verified) VALUES('city_admin',$1,$2,true) RETURNING id,role`,[phone,fullName]);else await client.query('UPDATE users SET full_name=$1,updated_at=now() WHERE id=$2',[fullName,user.rows[0].id]);await client.query(`INSERT INTO staff_credentials(user_id,password_hash) VALUES($1,crypt($2,gen_salt('bf'))) ON CONFLICT(user_id) DO UPDATE SET password_hash=crypt($2,gen_salt('bf')),updated_at=now()`,[user.rows[0].id,accessCode]);const assigned=await client.query(`INSERT INTO city_admin_assignments(user_id,city_id,permissions,created_by) VALUES($1,$2,$3::jsonb,$4) ON CONFLICT(user_id) DO UPDATE SET city_id=excluded.city_id,permissions=excluded.permissions,is_active=true,updated_at=now() RETURNING *`,[user.rows[0].id,cityId,JSON.stringify(permissions),req.user.sub]);await client.query(`INSERT INTO admin_audit_log(actor_user_id,target_user_id,city_id,action,details) VALUES($1,$2,$3,'city_admin.saved',$4::jsonb)`,[req.user.sub,user.rows[0].id,cityId,JSON.stringify({permissions})]);await client.query('COMMIT');res.status(201).json({assignment:assigned.rows[0]});}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}}));
app.patch('/v1/admin/city-users/:id', auth('admin'), asyncRoute(async (req,res)=>{const permissions=normalizePermissions(req.body.permissions);const isActive=req.body.isActive!==false;const cityId=req.body.cityId;const result=await pool.query(`UPDATE city_admin_assignments SET city_id=COALESCE($1,city_id),permissions=$2::jsonb,is_active=$3,updated_at=now() WHERE user_id=$4 RETURNING *`,[cityId||null,JSON.stringify(permissions),isActive,req.params.id]);if(!result.rowCount)return res.status(404).json({error:'CITY_USER_NOT_FOUND'});await pool.query(`INSERT INTO admin_audit_log(actor_user_id,target_user_id,city_id,action,details) VALUES($1,$2,$3,'city_admin.permissions_changed',$4::jsonb)`,[req.user.sub,req.params.id,result.rows[0].city_id,JSON.stringify({permissions,isActive})]);res.json({assignment:result.rows[0]});}));

app.get('/v1/city-admin/context', auth('admin','city_admin'), cityPermission('orders.read'), asyncRoute(async (req,res)=>{if(!req.cityScope)return res.json({role:'admin',unrestricted:true});res.json({role:'city_admin',city:{id:req.cityScope.city_id,name:req.cityScope.city_name,governorate:req.cityScope.governorate},permissions:req.cityScope.permissions});}));
app.get('/v1/city-admin/orders', auth('admin','city_admin'), cityPermission('orders.read'), asyncRoute(async (req,res)=>{const values=[];let where='';if(req.cityScope){values.push(req.cityScope.city_id);where='WHERE o.city_id=$1';}const rows=await pool.query(`SELECT o.*,u.full_name customer_name,m.display_name merchant_name,ru.full_name rider_name FROM orders o JOIN users u ON u.id=o.customer_id JOIN merchants m ON m.id=o.merchant_id LEFT JOIN riders r ON r.id=o.rider_id LEFT JOIN users ru ON ru.id=r.user_id ${where} ORDER BY o.created_at DESC LIMIT 200`,values);res.json({orders:rows.rows});}));
app.get('/v1/city-admin/riders', auth('admin','city_admin'), cityPermission('riders.read'), asyncRoute(async (req,res)=>{const values=[];let where='';if(req.cityScope){values.push(req.cityScope.city_id);where='WHERE r.city_id=$1';}const rows=await pool.query(`SELECT r.id,u.full_name,u.phone,r.vehicle_type,r.verification,r.is_available,r.probation_ends_at,r.city_id FROM riders r JOIN users u ON u.id=r.user_id ${where} ORDER BY r.is_available DESC,u.full_name`,values);res.json({riders:rows.rows});}));
app.patch('/v1/city-admin/riders/:id/availability', auth('admin','city_admin'), cityPermission('riders.manage'), asyncRoute(async (req,res)=>{const values=[req.body.isAvailable===true,req.params.id];let cityCheck='';if(req.cityScope){values.push(req.cityScope.city_id);cityCheck=' AND city_id=$3';}const result=await pool.query(`UPDATE riders SET is_available=$1 WHERE id=$2 AND verification='approved'${cityCheck} RETURNING id,is_available`,values);if(!result.rowCount)return res.status(404).json({error:'RIDER_NOT_FOUND_IN_CITY'});res.json({rider:result.rows[0]});}));
app.post('/v1/city-admin/orders/:id/assign', auth('admin','city_admin'), cityPermission('orders.manage'), asyncRoute(async (req,res)=>{const {riderId}=req.body;const values=[riderId,req.params.id];let cityCheck='';if(req.cityScope){values.push(req.cityScope.city_id);cityCheck=' AND o.city_id=$3 AND r.city_id=$3';}const result=await pool.query(`UPDATE orders o SET rider_id=r.id,status='assigned',updated_at=now() FROM riders r WHERE r.id=$1 AND o.id=$2 AND o.status='awaiting_rider' AND r.verification='approved' AND r.is_available=true${cityCheck} RETURNING o.id,o.public_code,o.status`,values);if(!result.rowCount)return res.status(409).json({error:'ORDER_OR_RIDER_NOT_AVAILABLE_IN_CITY'});await pool.query(`INSERT INTO order_events(order_id,actor_user_id,status,note) VALUES($1,$2,'assigned','إسناد يدوي بواسطة إدارة المدينة')`,[req.params.id,req.user.sub]);res.json({order:result.rows[0]});}));

app.get('/v1/admin/commission-rules',auth('admin'),asyncRoute(async(_req,res)=>{const rows=await pool.query(`SELECT r.*,c.name city_name FROM commission_rules r LEFT JOIN cities c ON c.id=r.city_id ORDER BY r.created_at DESC`);res.json({rules:rows.rows});}));
app.post('/v1/admin/commission-rules',auth('admin'),asyncRoute(async(req,res)=>{const {cityId,merchantCategory,calculationType,value,minimumAmount=0,maximumAmount}=req.body;if(!['percentage','fixed'].includes(calculationType)||!Number.isFinite(Number(value))||Number(value)<0||(calculationType==='percentage'&&Number(value)>100))return res.status(400).json({error:'INVALID_COMMISSION_RULE'});const row=await pool.query(`INSERT INTO commission_rules(city_id,merchant_category,calculation_type,value,minimum_amount,maximum_amount,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[cityId||null,merchantCategory||null,calculationType,Number(value),Number(minimumAmount)||0,maximumAmount===''||maximumAmount==null?null:Number(maximumAmount),req.user.sub]);res.status(201).json({rule:row.rows[0]});}));
app.patch('/v1/admin/commission-rules/:id',auth('admin'),asyncRoute(async(req,res)=>{const row=await pool.query(`UPDATE commission_rules SET is_active=$1,updated_at=now() WHERE id=$2 RETURNING *`,[req.body.isActive===true,req.params.id]);if(!row.rowCount)return res.status(404).json({error:'RULE_NOT_FOUND'});res.json({rule:row.rows[0]});}));
app.get('/v1/admin/partner-requests',auth('admin'),asyncRoute(async(_req,res)=>{const rows=await pool.query(`SELECT p.*,c.name city_name,u.full_name requester_name FROM city_partner_requests p JOIN cities c ON c.id=p.city_id JOIN users u ON u.id=p.requested_by ORDER BY p.created_at DESC`);res.json({requests:rows.rows});}));
app.patch('/v1/admin/partner-requests/:id',auth('admin'),asyncRoute(async(req,res)=>{if(!['approved','rejected'].includes(req.body.status))return res.status(400).json({error:'INVALID_REVIEW'});const row=await pool.query(`UPDATE city_partner_requests SET status=$1,reviewed_by=$2,reviewed_at=now() WHERE id=$3 AND status='pending' RETURNING *`,[req.body.status,req.user.sub,req.params.id]);if(!row.rowCount)return res.status(409).json({error:'REQUEST_ALREADY_REVIEWED'});res.json({request:row.rows[0]});}));
app.post('/v1/city-admin/partner-requests',auth('city_admin'),cityPermission('partners.request'),asyncRoute(async(req,res)=>{const {partnerType,fullName,phone,details={}}=req.body;if(!['merchant','rider'].includes(partnerType)||!fullName||!/^01\d{9}$/.test(String(phone||'')))return res.status(400).json({error:'INVALID_PARTNER_REQUEST'});const row=await pool.query(`INSERT INTO city_partner_requests(city_id,requested_by,partner_type,full_name,phone,details) VALUES($1,$2,$3,$4,$5,$6::jsonb) RETURNING *`,[req.cityScope.city_id,req.user.sub,partnerType,fullName,phone,JSON.stringify(details)]);res.status(201).json({request:row.rows[0]});}));
app.get('/v1/city-admin/partner-requests',auth('city_admin'),cityPermission('partners.request'),asyncRoute(async(req,res)=>{const rows=await pool.query(`SELECT * FROM city_partner_requests WHERE city_id=$1 ORDER BY created_at DESC`,[req.cityScope.city_id]);res.json({requests:rows.rows});}));

app.use((error, _req, res, _next) => { console.error(error); res.status(500).json({ error: 'INTERNAL_ERROR' }); });
app.listen(port, () => console.log(`Khalasa API listening on :${port}`));
