import 'dotenv/config';
import crypto from 'node:crypto';
import express from 'express';
import cors from 'cors';
import jwt from 'jsonwebtoken';
import pg from 'pg';
const { Pool } = pg;

const required = ['DATABASE_URL', 'JWT_SECRET'];
for (const name of required) if (!process.env[name]) throw new Error(`${name} is required`);
const app = express();
const port = Number(process.env.PORT || 8080);
const commissionRate = Number(process.env.PLATFORM_COMMISSION_RATE || 0.12);
const allowedOrigins = (process.env.CORS_ORIGINS || '').split(',').filter(Boolean);
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: process.env.NODE_ENV === 'production' ? { rejectUnauthorized: false } : false });
app.use(cors({ origin(origin, callback) { if (!origin || allowedOrigins.includes(origin)) return callback(null, true); callback(new Error('CORS_NOT_ALLOWED')); } }));
app.use(express.json({ limit: '1mb' }));

const requestWindows = new Map();
function rateLimit({ limit = 5, windowMs = 10 * 60 * 1000, key = req => req.ip }) {
  return (req, res, next) => {
    const now = Date.now();
    const bucketKey = `${req.path}:${key(req)}`;
    const bucket = requestWindows.get(bucketKey);
    if (!bucket || bucket.resetAt <= now) {
      requestWindows.set(bucketKey, { count: 1, resetAt: now + windowMs });
      return next();
    }
    if (bucket.count >= limit) {
      res.set('Retry-After', String(Math.ceil((bucket.resetAt - now) / 1000)));
      return res.status(429).json({ error: 'TOO_MANY_ATTEMPTS' });
    }
    bucket.count += 1;
    next();
  };
}
const authRateLimit = rateLimit({ limit: 8, key: req => `${req.ip}:${String(req.body?.phone || '')}` });
app.use((req, res, next) => ['/v1/staff/login', '/v1/auth/request-otp', '/v1/auth/verify-otp'].includes(req.path) ? authRateLimit(req, res, next) : next());

const asyncRoute = handler => (req, res, next) => Promise.resolve(handler(req, res, next)).catch(next);
const publicCode = () => `KH-${Date.now().toString(36).toUpperCase()}-${crypto.randomBytes(2).toString('hex').toUpperCase()}`;
const otpHash = otp => crypto.createHash('sha256').update(String(otp)).digest('hex');
function customerOrderView(order, deliveryOtp) { const { delivery_otp_hash: _otpHash, idempotency_key: _idempotencyKey, ...safe } = order; return deliveryOtp ? { ...safe, deliveryOtp } : safe; }
function tokenFor(user) { return jwt.sign({ sub: user.id, role: user.role, phone: user.phone }, process.env.JWT_SECRET, { expiresIn: ['admin','city_admin'].includes(user.role) ? '8h' : '7d' }); }
function auth(...roles) { return (req, res, next) => { try { const raw = req.headers.authorization?.replace(/^Bearer\s+/i, ''); if (!raw) return res.status(401).json({ error: 'AUTH_REQUIRED' }); const user = jwt.verify(raw, process.env.JWT_SECRET); if (roles.length && !roles.includes(user.role)) return res.status(403).json({ error: 'FORBIDDEN' }); req.user = user; next(); } catch { res.status(401).json({ error: 'INVALID_TOKEN' }); } }; }
const cityPermissions = ['orders.read','orders.manage','riders.read','riders.manage','partners.request'];
function normalizePermissions(value = {}) { return Object.fromEntries(cityPermissions.map(key => [key, value[key] === true])); }
function cityPermission(permission) { return asyncRoute(async (req, res, next) => {
  if (req.user.role === 'admin') { req.cityScope = null; return next(); }
  const result = await pool.query(`SELECT a.city_id,a.permissions,c.name city_name,c.governorate FROM city_admin_assignments a JOIN cities c ON c.id=a.city_id WHERE a.user_id=$1 AND a.is_active=true AND c.is_active=true`, [req.user.sub]);
  if (!result.rowCount) return res.status(403).json({ error:'CITY_ACCESS_DISABLED' });
  const assignment = result.rows[0];
  if (assignment.permissions?.[permission] !== true) return res.status(403).json({ error:'CITY_PERMISSION_REQUIRED', permission });
  req.cityScope = assignment;
  next();
}); }
function transitionAllowed(from, to) { return ({ awaiting_merchant:['preparing','cancelled'], preparing:['awaiting_rider','cancelled'], awaiting_rider:['assigned','cancelled'], assigned:['picked_up','cancelled'], picked_up:['delivered'], delivered:[], cancelled:[] })[from]?.includes(to); }
async function deliverOtp({ phone, email }, otp) {
  if(process.env.OTP_PROVIDER==='resend_email'){
    if(!process.env.RESEND_API_KEY||!process.env.OTP_EMAIL_FROM)throw new Error('OTP_PROVIDER_NOT_CONFIGURED');
    const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${process.env.RESEND_API_KEY}`},body:JSON.stringify({from:process.env.OTP_EMAIL_FROM,to:[email],subject:'رمز التحقق من خالصة',html:`<div dir="rtl" style="font-family:Arial,sans-serif;line-height:1.8"><h2>رمز التحقق من خالصة</h2><p>استخدم الرمز التالي لإكمال تسجيل الدخول:</p><p style="font-size:30px;font-weight:700;letter-spacing:6px">${otp}</p><p>تنتهي صلاحية الرمز خلال 5 دقائق. لا تشاركه مع أي شخص.</p></div>`})});
    if(!response.ok)throw new Error(`OTP_DELIVERY_FAILED_${response.status}`);
    return;
  }
  if(process.env.OTP_PROVIDER==='webhook'){
    if(!process.env.OTP_WEBHOOK_URL)throw new Error('OTP_PROVIDER_NOT_CONFIGURED');
    const response=await fetch(process.env.OTP_WEBHOOK_URL,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${process.env.OTP_WEBHOOK_SECRET||''}`},body:JSON.stringify({phone,otp,purpose:'customer_login'})});
    if(!response.ok)throw new Error(`OTP_DELIVERY_FAILED_${response.status}`);
    return;
  }
  if(process.env.OTP_PROVIDER==='meta_whatsapp'){
    const requiredMeta=['WHATSAPP_ACCESS_TOKEN','WHATSAPP_PHONE_NUMBER_ID','WHATSAPP_TEMPLATE_NAME','WHATSAPP_GRAPH_VERSION'];
    if(requiredMeta.some(name=>!process.env[name]))throw new Error('OTP_PROVIDER_NOT_CONFIGURED');
    const destination=`20${phone.slice(1)}`;
    const response=await fetch(`https://graph.facebook.com/${process.env.WHATSAPP_GRAPH_VERSION}/${process.env.WHATSAPP_PHONE_NUMBER_ID}/messages`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${process.env.WHATSAPP_ACCESS_TOKEN}`},body:JSON.stringify({messaging_product:'whatsapp',to:destination,type:'template',template:{name:process.env.WHATSAPP_TEMPLATE_NAME,language:{code:process.env.WHATSAPP_TEMPLATE_LANGUAGE||'ar'},components:[{type:'body',parameters:[{type:'text',text:otp}]},{type:'button',sub_type:'url',index:'0',parameters:[{type:'text',text:otp}]}]}})});
    if(!response.ok)throw new Error(`OTP_DELIVERY_FAILED_${response.status}`);
    return;
  }
  throw new Error('OTP_PROVIDER_NOT_CONFIGURED');
}

app.get('/health', asyncRoute(async (_req, res) => { await pool.query('SELECT 1'); res.json({ ok: true, service: 'khalasa-api' }); }));

app.post('/v1/staff/login', asyncRoute(async (req,res)=>{const phone=String(req.body.phone||''),accessCode=String(req.body.accessCode||'');if(!/^01\d{9}$/.test(phone)||accessCode.length<8)return res.status(400).json({error:'INVALID_STAFF_LOGIN'});if(phone===process.env.OWNER_PHONE&&process.env.OWNER_ACCESS_CODE){const valid=crypto.timingSafeEqual(crypto.createHash('sha256').update(accessCode).digest(),crypto.createHash('sha256').update(process.env.OWNER_ACCESS_CODE).digest());if(!valid)return res.status(401).json({error:'INVALID_STAFF_LOGIN'});const owner=await pool.query(`INSERT INTO users(role,phone,full_name,is_phone_verified) VALUES('admin',$1,'مالك خالصة',true) ON CONFLICT(phone) DO UPDATE SET role='admin',is_phone_verified=true,updated_at=now() RETURNING id,role,phone,full_name`,[phone]);const user=owner.rows[0];return res.json({token:tokenFor(user),user:{id:user.id,role:user.role,phone:user.phone,fullName:user.full_name}});}const found=await pool.query(`SELECT u.id,u.role,u.phone,u.full_name,sc.password_hash FROM users u JOIN staff_credentials sc ON sc.user_id=u.id AND sc.is_active=true WHERE u.phone=$1 AND u.role IN ('admin','city_admin')`,[phone]);if(!found.rowCount)return res.status(401).json({error:'INVALID_STAFF_LOGIN'});const user=found.rows[0];const check=await pool.query('SELECT crypt($1,$2)=$2 AS valid',[accessCode,user.password_hash]);if(!check.rows[0].valid)return res.status(401).json({error:'INVALID_STAFF_LOGIN'});res.json({token:tokenFor(user),user:{id:user.id,role:user.role,phone:user.phone,fullName:user.full_name}});}));
app.get('/v1/admin/me',auth('admin'),asyncRoute(async(req,res)=>res.json({ok:true,user:req.user})));
app.get('/v1/admin/main-users',auth('admin'),asyncRoute(async(_req,res)=>{const rows=await pool.query(`SELECT u.id,u.full_name,u.phone,COALESCE(sc.is_active,true) is_active FROM users u LEFT JOIN staff_credentials sc ON sc.user_id=u.id WHERE u.role='admin' ORDER BY u.created_at`);res.json({users:rows.rows});}));
app.post('/v1/admin/main-users',auth('admin'),asyncRoute(async(req,res)=>{const {fullName,phone,accessCode}=req.body;if(!fullName||!/^01\d{9}$/.test(String(phone||''))||String(accessCode||'').length<8)return res.status(400).json({error:'ADMIN_USER_FIELDS_REQUIRED'});const client=await pool.connect();try{await client.query('BEGIN');let user=await client.query('SELECT id,role FROM users WHERE phone=$1',[phone]);if(user.rowCount&&user.rows[0].role!=='admin'){await client.query('ROLLBACK');return res.status(409).json({error:'PHONE_BELONGS_TO_ANOTHER_ROLE'});}if(!user.rowCount)user=await client.query(`INSERT INTO users(role,phone,full_name,is_phone_verified) VALUES('admin',$1,$2,true) RETURNING id`,[phone,fullName]);else await client.query('UPDATE users SET full_name=$1,updated_at=now() WHERE id=$2',[fullName,user.rows[0].id]);await client.query(`INSERT INTO staff_credentials(user_id,password_hash,is_active) VALUES($1,crypt($2,gen_salt('bf')),true) ON CONFLICT(user_id) DO UPDATE SET password_hash=crypt($2,gen_salt('bf')),is_active=true,updated_at=now()`,[user.rows[0].id,accessCode]);await client.query(`INSERT INTO admin_audit_log(actor_user_id,target_user_id,action,details) VALUES($1,$2,'main_admin.saved',$3::jsonb)`,[req.user.sub,user.rows[0].id,JSON.stringify({phone})]);await client.query('COMMIT');res.status(201).json({ok:true});}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}}));
app.patch('/v1/admin/main-users/:id',auth('admin'),asyncRoute(async(req,res)=>{if(req.params.id===req.user.sub)return res.status(409).json({error:'CANNOT_DISABLE_SELF'});const row=await pool.query(`UPDATE staff_credentials SET is_active=$1,updated_at=now() WHERE user_id=$2 RETURNING user_id,is_active`,[req.body.isActive===true,req.params.id]);if(!row.rowCount)return res.status(404).json({error:'ADMIN_USER_NOT_FOUND'});res.json({user:row.rows[0]});}));

app.post('/v1/auth/request-otp', asyncRoute(async (req, res) => {
  const phone=String(req.body.phone||''),email=String(req.body.email||'').trim().toLowerCase();if(!/^01\d{9}$/.test(phone))return res.status(400).json({error:'INVALID_EGYPTIAN_PHONE'});
  if(process.env.OTP_PROVIDER==='resend_email'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return res.status(400).json({error:'INVALID_EMAIL'});
  const existing=await pool.query('SELECT role FROM users WHERE phone=$1',[phone]);if(existing.rowCount&&existing.rows[0].role!=='customer')return res.status(403).json({error:'STAFF_ACCOUNT_REQUIRES_STAFF_LOGIN'});
  if(process.env.NODE_ENV==='production'&&!['webhook','meta_whatsapp','resend_email'].includes(process.env.OTP_PROVIDER))return res.status(503).json({error:'OTP_PROVIDER_NOT_CONFIGURED'});
  const otp=crypto.randomInt(100000,1000000).toString(),hash=crypto.createHmac('sha256',process.env.JWT_SECRET).update(`${phone}:${otp}`).digest('hex');
  await pool.query(`UPDATE auth_challenges SET consumed_at=now() WHERE phone=$1 AND purpose='customer_login' AND consumed_at IS NULL`,[phone]);
  await pool.query(`INSERT INTO auth_challenges(phone,email,otp_hash,expires_at) VALUES($1,$2,$3,now()+interval '5 minutes')`,[phone,email||null,hash]);
  if(process.env.NODE_ENV==='production'){try{await deliverOtp({phone,email},otp);}catch(error){if(error.message==='OTP_PROVIDER_NOT_CONFIGURED')return res.status(503).json({error:'OTP_PROVIDER_NOT_CONFIGURED'});return res.status(502).json({error:'OTP_DELIVERY_FAILED'});}}
  res.status(202).json({accepted:true,...(process.env.NODE_ENV!=='production'?{devOtp:otp}:{})});
}));
app.post('/v1/auth/verify-otp',asyncRoute(async(req,res)=>{const phone=String(req.body.phone||''),fullName=String(req.body.fullName||'').trim(),otp=String(req.body.otp||'');if(!/^01\d{9}$/.test(phone)||!fullName||!/^\d{6}$/.test(otp))return res.status(400).json({error:'INVALID_VERIFICATION_FIELDS'});const challenge=await pool.query(`SELECT id,email,otp_hash,attempts FROM auth_challenges WHERE phone=$1 AND purpose='customer_login' AND consumed_at IS NULL AND expires_at>now() ORDER BY created_at DESC LIMIT 1`,[phone]);if(!challenge.rowCount||challenge.rows[0].attempts>=5)return res.status(401).json({error:'OTP_INVALID_OR_EXPIRED'});const hash=crypto.createHmac('sha256',process.env.JWT_SECRET).update(`${phone}:${otp}`).digest('hex');const valid=crypto.timingSafeEqual(Buffer.from(hash,'hex'),Buffer.from(challenge.rows[0].otp_hash,'hex'));if(!valid){await pool.query('UPDATE auth_challenges SET attempts=attempts+1 WHERE id=$1',[challenge.rows[0].id]);return res.status(401).json({error:'OTP_INVALID_OR_EXPIRED'});}const client=await pool.connect();try{await client.query('BEGIN');await client.query('UPDATE auth_challenges SET consumed_at=now() WHERE id=$1',[challenge.rows[0].id]);let user=await client.query('SELECT id,role,phone,full_name,email FROM users WHERE phone=$1',[phone]);if(user.rowCount&&user.rows[0].role!=='customer'){await client.query('ROLLBACK');return res.status(403).json({error:'STAFF_ACCOUNT_REQUIRES_STAFF_LOGIN'});}if(!user.rowCount)user=await client.query(`INSERT INTO users(role,phone,full_name,email,is_phone_verified,is_email_verified) VALUES('customer',$1,$2,$3,false,true) RETURNING id,role,phone,full_name,email`,[phone,fullName,challenge.rows[0].email]);else user=await client.query(`UPDATE users SET full_name=$1,email=COALESCE($2,email),is_email_verified=true,updated_at=now() WHERE id=$3 RETURNING id,role,phone,full_name,email`,[fullName,challenge.rows[0].email,user.rows[0].id]);await client.query('COMMIT');res.json({token:tokenFor(user.rows[0]),user:user.rows[0]});}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}}));
app.post('/v1/auth/session',(_req,res)=>res.status(410).json({error:'OTP_VERIFICATION_REQUIRED'}));

app.post('/v1/orders', auth('customer'), asyncRoute(async (req, res) => {
  const { merchantId, items, deliveryAddress, deliveryLat, deliveryLng, paymentMethod = 'cod' } = req.body;
  if (!merchantId || !Array.isArray(items) || !items.length || !deliveryAddress) return res.status(400).json({ error: 'ORDER_FIELDS_REQUIRED' });
  if (!['cod','wallet','card'].includes(paymentMethod)) return res.status(400).json({ error: 'INVALID_PAYMENT_METHOD' });
  const requested = items.map(item => ({ productId:String(item.productId || ''),quantity:Number(item.quantity || item.qty) }));
  if (requested.some(item => !item.productId || !Number.isInteger(item.quantity) || item.quantity < 1 || item.quantity > 50)) return res.status(400).json({ error: 'INVALID_ITEMS' });
  const idempotencyKey=String(req.headers['x-idempotency-key']||'');
  if(!/^[A-Za-z0-9_-]{16,100}$/.test(idempotencyKey))return res.status(400).json({error:'IDEMPOTENCY_KEY_REQUIRED'});
  const client = await pool.connect();
  try {
    await client.query('BEGIN');
    const replay=await client.query('SELECT * FROM orders WHERE idempotency_key=$1 AND customer_id=$2',[idempotencyKey,req.user.sub]);
    if(replay.rowCount){await client.query('COMMIT');return res.json({order:customerOrderView(replay.rows[0]),replayed:true});}
    const merchant = await client.query('SELECT city_id,category FROM merchants WHERE id=$1 AND verification=$2 AND is_accepting_orders=true',[merchantId,'approved']);
    if(!merchant.rowCount){await client.query('ROLLBACK');return res.status(404).json({error:'MERCHANT_NOT_AVAILABLE'});}
    const productIds=[...new Set(requested.map(item=>item.productId))];
    const products=await client.query('SELECT id,name,price FROM products WHERE merchant_id=$1 AND is_available=true AND id=ANY($2::uuid[])',[merchantId,productIds]);
    const catalog=new Map(products.rows.map(product=>[product.id,product]));
    if(catalog.size!==productIds.length){await client.query('ROLLBACK');return res.status(409).json({error:'PRODUCT_NOT_AVAILABLE'});}
    const normalized=requested.map(item=>({productName:catalog.get(item.productId).name,quantity:item.quantity,unitPrice:Number(catalog.get(item.productId).price)}));
    const merchandiseTotal=normalized.reduce((sum,item)=>sum+item.quantity*item.unitPrice,0),deliveryFee=20,otp=crypto.randomInt(1000,10000).toString();
    const selected=await client.query(`SELECT calculation_type,value,minimum_amount,maximum_amount FROM commission_rules WHERE is_active=true AND (city_id IS NULL OR city_id=$1) AND (merchant_category IS NULL OR merchant_category=$2) ORDER BY (city_id IS NOT NULL)::int DESC,(merchant_category IS NOT NULL)::int DESC,created_at DESC LIMIT 1`,[merchant.rows[0].city_id,merchant.rows[0].category]);
    const rule=selected.rows[0];let commission=rule?(rule.calculation_type==='fixed'?Number(rule.value):merchandiseTotal*Number(rule.value)/100):merchandiseTotal*commissionRate;if(rule){commission=Math.max(commission,Number(rule.minimum_amount||0));if(rule.maximum_amount!=null)commission=Math.min(commission,Number(rule.maximum_amount));}commission=Number(Math.min(commission,merchandiseTotal).toFixed(2));const merchantPayout=Number((merchandiseTotal-commission).toFixed(2));
    const created=await client.query(`INSERT INTO orders(public_code,customer_id,merchant_id,city_id,delivery_address,delivery_lat,delivery_lng,payment_method,merchandise_total,delivery_fee,platform_commission,merchant_payout,delivery_otp_hash,idempotency_key) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING *`,[publicCode(),req.user.sub,merchantId,merchant.rows[0].city_id,deliveryAddress,deliveryLat||null,deliveryLng||null,paymentMethod,merchandiseTotal,deliveryFee,commission,merchantPayout,otpHash(otp),idempotencyKey]);
    const order=created.rows[0];for(const item of normalized)await client.query('INSERT INTO order_items(order_id,product_name,quantity,unit_price) VALUES($1,$2,$3,$4)',[order.id,item.productName,item.quantity,item.unitPrice]);await client.query('INSERT INTO order_events(order_id,actor_user_id,status,note) VALUES($1,$2,$3,$4)',[order.id,req.user.sub,'awaiting_merchant','تم إنشاء الطلب']);await client.query('COMMIT');res.status(201).json({order:customerOrderView(order,otp)});
  } catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}
}));

app.get('/v1/merchant/orders', auth('merchant'), asyncRoute(async (req, res) => { const rows = await pool.query(`SELECT o.* FROM orders o JOIN merchants m ON m.id=o.merchant_id WHERE m.owner_user_id=$1 AND o.status IN ('awaiting_merchant','preparing') ORDER BY o.created_at DESC`, [req.user.sub]); res.json({ orders: rows.rows }); }));
app.post('/v1/orders/:id/merchant-accept', auth('merchant'), asyncRoute(async (req, res) => { const prepMinutes = Number(req.body.prepMinutes || 20); const order = await pool.query(`SELECT o.* FROM orders o JOIN merchants m ON m.id=o.merchant_id WHERE o.id=$1 AND m.owner_user_id=$2`, [req.params.id, req.user.sub]); if (!order.rowCount) return res.status(404).json({ error: 'ORDER_NOT_FOUND' }); if (!transitionAllowed(order.rows[0].status, 'preparing')) return res.status(409).json({ error: 'INVALID_STATE' }); await pool.query(`UPDATE orders SET status='preparing',prep_minutes=$1,updated_at=now() WHERE id=$2`, [prepMinutes, req.params.id]); await pool.query(`INSERT INTO order_events(order_id,actor_user_id,status,note) VALUES($1,$2,'preparing',$3)`, [req.params.id, req.user.sub, `وقت التجهيز ${prepMinutes} دقيقة`]); res.json({ ok:true }); }));
app.post('/v1/orders/:id/ready', auth('merchant'), asyncRoute(async (req, res) => { const result = await pool.query(`UPDATE orders o SET status='awaiting_rider',updated_at=now() FROM merchants m WHERE o.id=$1 AND o.status='preparing' AND m.id=o.merchant_id AND m.owner_user_id=$2 RETURNING o.id`, [req.params.id,req.user.sub]); if (!result.rowCount) return res.status(409).json({ error:'INVALID_STATE_OR_OWNER' }); await pool.query(`INSERT INTO order_events(order_id,actor_user_id,status,note) VALUES($1,$2,'awaiting_rider','الطلب جاهز للاستلام')`, [req.params.id,req.user.sub]); res.json({ ok:true }); }));
app.get('/v1/rider/offers', auth('rider'), asyncRoute(async (req, res) => { const rows = await pool.query(`SELECT o.id,o.public_code,o.merchant_id,o.delivery_address,o.delivery_fee,o.created_at FROM orders o JOIN riders r ON r.user_id=$1 AND r.verification='approved' AND r.is_available=true WHERE o.status='awaiting_rider' AND o.city_id=r.city_id ORDER BY o.created_at ASC LIMIT 20`,[req.user.sub]); res.json({ orders:rows.rows }); }));
app.post('/v1/orders/:id/rider-accept', auth('rider'), asyncRoute(async (req,res) => { const rider = await pool.query('SELECT id,city_id FROM riders WHERE user_id=$1 AND verification=$2 AND is_available=true',[req.user.sub,'approved']); if(!rider.rowCount) return res.status(403).json({error:'RIDER_NOT_AVAILABLE_OR_APPROVED'}); const result=await pool.query(`UPDATE orders SET status='assigned',rider_id=$1,updated_at=now() WHERE id=$2 AND city_id=$3 AND status='awaiting_rider' RETURNING id`,[rider.rows[0].id,req.params.id,rider.rows[0].city_id]); if(!result.rowCount)return res.status(409).json({error:'ORDER_ALREADY_TAKEN_OR_OUTSIDE_CITY'}); await pool.query(`INSERT INTO order_events(order_id,actor_user_id,status,note) VALUES($1,$2,'assigned','تم قبول الطلب بواسطة المندوب')`,[req.params.id,req.user.sub]);res.json({ok:true}); }));
app.post('/v1/orders/:id/pickup', auth('rider'), asyncRoute(async (req,res) => { const result=await pool.query(`UPDATE orders o SET status='picked_up',updated_at=now() FROM riders r WHERE o.id=$1 AND o.status='assigned' AND o.rider_id=r.id AND r.user_id=$2 RETURNING o.id`,[req.params.id,req.user.sub]);if(!result.rowCount)return res.status(409).json({error:'ORDER_NOT_ASSIGNED_TO_RIDER'});await pool.query(`INSERT INTO order_events(order_id,actor_user_id,status,note) VALUES($1,$2,'picked_up','تم استلام الطلب من المحل')`,[req.params.id,req.user.sub]);res.json({ok:true}); }));
app.post('/v1/orders/:id/deliver', auth('rider'), asyncRoute(async (req,res) => { const order=await pool.query(`SELECT o.* FROM orders o JOIN riders r ON r.id=o.rider_id WHERE o.id=$1 AND r.user_id=$2`,[req.params.id,req.user.sub]); if(!order.rowCount)return res.status(404).json({error:'ORDER_NOT_ASSIGNED_TO_RIDER'}); if(order.rows[0].status!=='picked_up'||otpHash(req.body.otp)!==order.rows[0].delivery_otp_hash)return res.status(409).json({error:'INVALID_DELIVERY_CONFIRMATION'}); await pool.query(`UPDATE orders SET status='delivered',updated_at=now() WHERE id=$1`,[req.params.id]);await pool.query(`INSERT INTO order_events(order_id,actor_user_id,status,note) VALUES($1,$2,'delivered','تم التسليم برمز العميل')`,[req.params.id,req.user.sub]);res.json({ok:true}); }));
app.get('/v1/admin/orders', auth('admin','support'), asyncRoute(async (_req,res)=>{const rows=await pool.query(`SELECT o.*,u.full_name customer_name,m.display_name merchant_name FROM orders o JOIN users u ON u.id=o.customer_id JOIN merchants m ON m.id=o.merchant_id ORDER BY o.created_at DESC LIMIT 200`);res.json({orders:rows.rows});}));

app.get('/v1/admin/cities', auth('admin'), asyncRoute(async (_req,res)=>{const rows=await pool.query(`SELECT c.*,count(DISTINCT a.user_id)::int admin_count FROM cities c LEFT JOIN city_admin_assignments a ON a.city_id=c.id AND a.is_active=true GROUP BY c.id ORDER BY c.governorate,c.name`);res.json({cities:rows.rows});}));
app.post('/v1/admin/cities', auth('admin'), asyncRoute(async (req,res)=>{const {governorate,name,code}=req.body;if(!governorate||!name||!/^[a-z0-9-]{3,60}$/.test(String(code||'')))return res.status(400).json({error:'CITY_FIELDS_REQUIRED'});const row=await pool.query(`INSERT INTO cities(governorate,name,code) VALUES($1,$2,$3) RETURNING *`,[governorate,name,code]);res.status(201).json({city:row.rows[0]});}));
app.get('/v1/admin/city-users', auth('admin'), asyncRoute(async (_req,res)=>{const rows=await pool.query(`SELECT u.id,u.full_name,u.phone,a.city_id,c.name city_name,c.governorate,a.permissions,a.is_active,a.updated_at FROM city_admin_assignments a JOIN users u ON u.id=a.user_id JOIN cities c ON c.id=a.city_id ORDER BY c.name,u.full_name`);res.json({users:rows.rows});}));
app.post('/v1/admin/city-users', auth('admin'), asyncRoute(async (req,res)=>{const {fullName,phone,cityId,accessCode}=req.body;if(!fullName||!/^01\d{9}$/.test(String(phone||''))||!cityId||String(accessCode||'').length<8)return res.status(400).json({error:'CITY_USER_FIELDS_OR_CODE_REQUIRED'});const permissions=normalizePermissions(req.body.permissions);const client=await pool.connect();try{await client.query('BEGIN');let user=await client.query('SELECT id,role FROM users WHERE phone=$1',[phone]);if(user.rowCount&&user.rows[0].role!=='city_admin'){await client.query('ROLLBACK');return res.status(409).json({error:'PHONE_BELONGS_TO_ANOTHER_ROLE'});}if(!user.rowCount)user=await client.query(`INSERT INTO users(role,phone,full_name,is_phone_verified) VALUES('city_admin',$1,$2,true) RETURNING id,role`,[phone,fullName]);else await client.query('UPDATE users SET full_name=$1,updated_at=now() WHERE id=$2',[fullName,user.rows[0].id]);await client.query(`INSERT INTO staff_credentials(user_id,password_hash) VALUES($1,crypt($2,gen_salt('bf'))) ON CONFLICT(user_id) DO UPDATE SET password_hash=crypt($2,gen_salt('bf')),updated_at=now()`,[user.rows[0].id,accessCode]);const assigned=await client.query(`INSERT INTO city_admin_assignments(user_id,city_id,permissions,created_by) VALUES($1,$2,$3::jsonb,$4) ON CONFLICT(user_id) DO UPDATE SET city_id=excluded.city_id,permissions=excluded.permissions,is_active=true,updated_at=now() RETURNING *`,[user.rows[0].id,cityId,JSON.stringify(permissions),req.user.sub]);await client.query(`INSERT INTO admin_audit_log(actor_user_id,target_user_id,city_id,action,details) VALUES($1,$2,$3,'city_admin.saved',$4::jsonb)`,[req.user.sub,user.rows[0].id,cityId,JSON.stringify({permissions})]);await client.query('COMMIT');res.status(201).json({assignment:assigned.rows[0]});}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}}));
app.patch('/v1/admin/city-users/:id', auth('admin'), asyncRoute(async (req,res)=>{const permissions=normalizePermissions(req.body.permissions);const isActive=req.body.isActive!==false;const cityId=req.body.cityId;const result=await pool.query(`UPDATE city_admin_assignments SET city_id=COALESCE($1,city_id),permissions=$2::jsonb,is_active=$3,updated_at=now() WHERE user_id=$4 RETURNING *`,[cityId||null,JSON.stringify(permissions),isActive,req.params.id]);if(!result.rowCount)return res.status(404).json({error:'CITY_USER_NOT_FOUND'});await pool.query(`INSERT INTO admin_audit_log(actor_user_id,target_user_id,city_id,action,details) VALUES($1,$2,$3,'city_admin.permissions_changed',$4::jsonb)`,[req.user.sub,req.params.id,result.rows[0].city_id,JSON.stringify({permissions,isActive})]);res.json({assignment:result.rows[0]});}));

app.get('/v1/city-admin/context', auth('admin','city_admin'), cityPermission('orders.read'), asyncRoute(async (req,res)=>{if(!req.cityScope)return res.json({role:'admin',unrestricted:true});res.json({role:'city_admin',city:{id:req.cityScope.city_id,name:req.cityScope.city_name,governorate:req.cityScope.governorate},permissions:req.cityScope.permissions});}));
app.get('/v1/city-admin/orders', auth('admin','city_admin'), cityPermission('orders.read'), asyncRoute(async (req,res)=>{const values=[];let where='';if(req.cityScope){values.push(req.cityScope.city_id);where='WHERE o.city_id=$1';}const rows=await pool.query(`SELECT o.*,u.full_name customer_name,m.display_name merchant_name,ru.full_name rider_name FROM orders o JOIN users u ON u.id=o.customer_id JOIN merchants m ON m.id=o.merchant_id LEFT JOIN riders r ON r.id=o.rider_id LEFT JOIN users ru ON ru.id=r.user_id ${where} ORDER BY o.created_at DESC LIMIT 200`,values);res.json({orders:rows.rows});}));
app.get('/v1/city-admin/riders', auth('admin','city_admin'), cityPermission('riders.read'), asyncRoute(async (req,res)=>{const values=[];let where='';if(req.cityScope){values.push(req.cityScope.city_id);where='WHERE r.city_id=$1';}const rows=await pool.query(`SELECT r.id,u.full_name,u.phone,r.vehicle_type,r.verification,r.is_available,r.probation_ends_at,r.city_id FROM riders r JOIN users u ON u.id=r.user_id ${where} ORDER BY r.is_available DESC,u.full_name`,values);res.json({riders:rows.rows});}));
app.patch('/v1/city-admin/riders/:id/availability', auth('admin','city_admin'), cityPermission('riders.manage'), asyncRoute(async (req,res)=>{const values=[req.body.isAvailable===true,req.params.id];let cityCheck='';if(req.cityScope){values.push(req.cityScope.city_id);cityCheck=' AND city_id=$3';}const result=await pool.query(`UPDATE riders SET is_available=$1 WHERE id=$2 AND verification='approved'${cityCheck} RETURNING id,is_available`,values);if(!result.rowCount)return res.status(404).json({error:'RIDER_NOT_FOUND_IN_CITY'});res.json({rider:result.rows[0]});}));
app.post('/v1/city-admin/orders/:id/assign', auth('admin','city_admin'), cityPermission('orders.manage'), asyncRoute(async (req,res)=>{const {riderId}=req.body;const values=[riderId,req.params.id];let cityCheck='';if(req.cityScope){values.push(req.cityScope.city_id);cityCheck=' AND o.city_id=$3 AND r.city_id=$3';}const result=await pool.query(`UPDATE orders o SET rider_id=r.id,status='assigned',updated_at=now() FROM riders r WHERE r.id=$1 AND o.id=$2 AND o.status='awaiting_rider' AND r.verification='approved' AND r.is_available=true${cityCheck} RETURNING o.id,o.public_code,o.status`,values);if(!result.rowCount)return res.status(409).json({error:'ORDER_OR_RIDER_NOT_AVAILABLE_IN_CITY'});await pool.query(`INSERT INTO order_events(order_id,actor_user_id,status,note) VALUES($1,$2,'assigned','إسناد يدوي بواسطة إدارة المدينة')`,[req.params.id,req.user.sub]);res.json({order:result.rows[0]});}));

app.get('/v1/admin/commission-rules',auth('admin'),asyncRoute(async(_req,res)=>{const rows=await pool.query(`SELECT r.*,c.name city_name FROM commission_rules r LEFT JOIN cities c ON c.id=r.city_id ORDER BY r.created_at DESC`);res.json({rules:rows.rows});}));
app.post('/v1/admin/commission-rules',auth('admin'),asyncRoute(async(req,res)=>{const {cityId,merchantCategory,calculationType,value,minimumAmount=0,maximumAmount}=req.body;if(!['percentage','fixed'].includes(calculationType)||!Number.isFinite(Number(value))||Number(value)<0||(calculationType==='percentage'&&Number(value)>100))return res.status(400).json({error:'INVALID_COMMISSION_RULE'});const row=await pool.query(`INSERT INTO commission_rules(city_id,merchant_category,calculation_type,value,minimum_amount,maximum_amount,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[cityId||null,merchantCategory||null,calculationType,Number(value),Number(minimumAmount)||0,maximumAmount===''||maximumAmount==null?null:Number(maximumAmount),req.user.sub]);res.status(201).json({rule:row.rows[0]});}));
app.patch('/v1/admin/commission-rules/:id',auth('admin'),asyncRoute(async(req,res)=>{const row=await pool.query(`UPDATE commission_rules SET is_active=$1,updated_at=now() WHERE id=$2 RETURNING *`,[req.body.isActive===true,req.params.id]);if(!row.rowCount)return res.status(404).json({error:'RULE_NOT_FOUND'});res.json({rule:row.rows[0]});}));
app.get('/v1/admin/partner-requests',auth('admin'),asyncRoute(async(_req,res)=>{const rows=await pool.query(`SELECT p.*,c.name city_name,u.full_name requester_name FROM city_partner_requests p JOIN cities c ON c.id=p.city_id JOIN users u ON u.id=p.requested_by ORDER BY p.created_at DESC`);res.json({requests:rows.rows});}));
app.patch('/v1/admin/partner-requests/:id',auth('admin'),asyncRoute(async(req,res)=>{if(!['approved','rejected'].includes(req.body.status))return res.status(400).json({error:'INVALID_REVIEW'});const row=await pool.query(`UPDATE city_partner_requests SET status=$1,reviewed_by=$2,reviewed_at=now() WHERE id=$3 AND status='pending' RETURNING *`,[req.body.status,req.user.sub,req.params.id]);if(!row.rowCount)return res.status(409).json({error:'REQUEST_ALREADY_REVIEWED'});res.json({request:row.rows[0]});}));
app.post('/v1/city-admin/partner-requests',auth('city_admin'),cityPermission('partners.request'),asyncRoute(async(req,res)=>{const {partnerType,fullName,phone,details={}}=req.body;if(!['merchant','rider'].includes(partnerType)||!fullName||!/^01\d{9}$/.test(String(phone||'')))return res.status(400).json({error:'INVALID_PARTNER_REQUEST'});const row=await pool.query(`INSERT INTO city_partner_requests(city_id,requested_by,partner_type,full_name,phone,details) VALUES($1,$2,$3,$4,$5,$6::jsonb) RETURNING *`,[req.cityScope.city_id,req.user.sub,partnerType,fullName,phone,JSON.stringify(details)]);res.status(201).json({request:row.rows[0]});}));
app.get('/v1/city-admin/partner-requests',auth('city_admin'),cityPermission('partners.request'),asyncRoute(async(req,res)=>{const rows=await pool.query(`SELECT * FROM city_partner_requests WHERE city_id=$1 ORDER BY created_at DESC`,[req.cityScope.city_id]);res.json({requests:rows.rows});}));

app.use((error, _req, res, _next) => { console.error(error); res.status(500).json({ error: 'INTERNAL_ERROR' }); });
app.listen(port, () => console.log(`Khalasa API listening on :${port}`));
